import type { LevelDefinition, LotDef } from '../game/types';

/**
 * Data level. Tiap level: pulau hutan persegi yang tersusun dalam baris-baris di sekeliling
 * alun-alun tengah. Rel mengikuti tepi lahan yang sudah bersih. Pita k (zona jenis blok,
 * lebar `ringStep`) membiayai distrik k: distrik 0 di alun-alun (maks. 5 kavling, yang pertama
 * gedung utama), distrik k di baris kota bekas pita k-1 (layout.ts menata kavling ke blok-blok
 * grid; gedung besar `size: 2` mendapat satu blok). Tiap kavling terbuka begitu rel melewatinya.
 * Biaya tiap bangunan = porsi bobotnya dari hasil pita hutan distrik itu, jadi kota selesai
 * tepat saat hutan habis.
 * Untuk menambah level: salin satu objek di LEVELS lalu ubah distrik, bobot, pita, dan seed.
 */

const L = (building: string, variant: number, weight = 1): LotDef => ({ building, variant, weight });

export const LEVELS: LevelDefinition[] = [
  {
    id: 'hutan-cemara',
    name: 'Hutan Cemara',
    theme: 'forest',
    material: 'wood',
    ringStart: 4.5,
    ringStep: 2.5,
    districts: [
      { name: 'Alun-alun', lots: [L('balai-desa', 0, 4), L('rumah-makan', 0, 1.3), L('warung', 0), L('rumah-kayu', 0), L('rumah-papan', 0)] },
      {
        name: 'Kampung Cemara',
        lots: [
          L('sekolah', 0, 3.5),
          L('puskesmas', 0, 1.5),
          L('rumah-kayu', 1),
          L('rumah-papan', 1),
          L('warung', 1),
          L('rumah-panggung', 0, 1.2),
          L('rumah-kayu', 2),
          L('rumah-loteng', 0, 1.4),
          L('rumah-papan', 2),
          L('lumbung', 0, 1.4),
        ],
      },
      {
        name: 'Kampung Pinus',
        lots: [
          L('pasar', 0, 3.5),
          L('pemadam', 0, 1.6),
          L('rumah-makan', 1, 1.3),
          L('menara-air', 0, 2),
          L('rumah-loteng', 1, 1.4),
          L('rumah-kayu', 3),
          L('warung', 2),
          L('rumah-panggung', 1, 1.2),
          L('rumah-papan', 3),
          L('lumbung', 1, 1.4),
          L('rumah-kayu', 0),
          L('rumah-loteng', 2, 1.4),
          L('rumah-panggung', 2, 1.2),
          L('warung', 0),
        ],
      },
      {
        name: 'Kampung Jati',
        lots: [
          L('lapangan-bola', 0, 3),
          L('puskesmas', 1, 1.5),
          L('rumah-makan', 0, 1.3),
          L('menara-air', 1, 2),
          L('rumah-loteng', 0, 1.4),
          L('rumah-kayu', 1),
          L('rumah-papan', 0),
          L('lumbung', 2, 1.4),
          L('rumah-panggung', 0, 1.2),
          L('warung', 1),
          L('rumah-kayu', 2),
          L('rumah-papan', 1),
          L('rumah-loteng', 1, 1.4),
          L('rumah-panggung', 1, 1.2),
          L('rumah-kayu', 3),
          L('warung', 2),
          L('rumah-papan', 2),
          L('lumbung', 0, 1.4),
        ],
      },
      {
        name: 'Kampung Meranti',
        lots: [
          L('sekolah', 1, 3.5),
          L('pasar', 1, 3.5),
          L('pemadam', 0, 1.6),
          L('rumah-makan', 1, 1.3),
          L('menara-air', 0, 2),
          L('puskesmas', 0, 1.5),
          L('rumah-loteng', 2, 1.4),
          L('rumah-kayu', 0),
          L('rumah-panggung', 2, 1.2),
          L('rumah-papan', 3),
          L('warung', 0),
          L('lumbung', 1, 1.4),
          L('rumah-kayu', 1),
          L('rumah-loteng', 0, 1.4),
          L('rumah-papan', 0),
          L('rumah-panggung', 0, 1.2),
          L('warung', 2),
          L('rumah-kayu', 2),
          L('rumah-loteng', 1, 1.4),
          L('rumah-papan', 1),
          L('lumbung', 2, 1.4),
          L('rumah-kayu', 3),
        ],
      },
    ],
    bands: [
      { tree: 94, rock: 6 },
      { treeGold: 70, tree: 18, rock: 12 },
      { treeRed: 50, treeGold: 20, rock: 20, crystal: 10 },
      { treeRed: 58, rock: 24, crystal: 18 },
      { treeRed: 52, rock: 26, crystal: 22 },
    ],
    mapHalf: 18,
    seed: 1337,
    costScale: 1,
    completionBonus: 800,
  },
  {
    id: 'lembah-batu',
    name: 'Lembah Batu',
    theme: 'meadow',
    material: 'brick',
    ringStart: 4.5,
    ringStep: 2.5,
    districts: [
      { name: 'Alun-alun Batu', lots: [L('balai-kota', 0, 4), L('restoran', 0, 1.3), L('toko-roti', 0), L('ruko', 0), L('rumah-bata', 0)] },
      {
        name: 'Blok Granit',
        lots: [
          L('sekolah-bata', 0, 3.5),
          L('perpustakaan', 0, 1.5),
          L('rumah-bata', 1),
          L('ruko', 1),
          L('toko-roti', 1),
          L('rumah-bata-2', 0, 1.3),
          L('rumah-bata', 2),
          L('apartemen', 0, 1.6),
          L('ruko', 2),
          L('rumah-bata-2', 1, 1.3),
        ],
      },
      {
        name: 'Blok Marmer',
        lots: [
          L('rumah-sakit', 0, 4),
          L('kantor-polisi', 0, 1.5),
          L('restoran', 1, 1.3),
          L('menara-jam', 0, 2.2),
          L('apartemen', 1, 1.6),
          L('rumah-bata', 3),
          L('toko-roti', 2),
          L('rumah-bata-2', 2, 1.3),
          L('ruko', 0),
          L('rumah-bata', 0),
          L('apartemen', 2, 1.6),
          L('toko-roti', 0),
          L('rumah-bata-2', 0, 1.3),
          L('ruko', 1),
        ],
      },
      {
        name: 'Blok Andesit',
        lots: [
          L('stadion', 0, 3.5),
          L('pemadam-bata', 0, 1.6),
          L('perpustakaan', 1, 1.5),
          L('restoran', 2, 1.3),
          L('menara-jam', 1, 2.2),
          L('apartemen', 0, 1.6),
          L('rumah-bata', 1),
          L('ruko', 2),
          L('rumah-bata-2', 1, 1.3),
          L('toko-roti', 1),
          L('rumah-bata', 2),
          L('apartemen', 1, 1.6),
          L('ruko', 0),
          L('rumah-bata-2', 2, 1.3),
          L('toko-roti', 2),
          L('rumah-bata', 3),
          L('apartemen', 2, 1.6),
          L('ruko', 1),
        ],
      },
      {
        name: 'Blok Basal',
        lots: [
          L('sekolah-bata', 1, 3.5),
          L('rumah-sakit', 1, 4),
          L('kantor-polisi', 0, 1.5),
          L('restoran', 0, 1.3),
          L('pemadam-bata', 0, 1.6),
          L('perpustakaan', 0, 1.5),
          L('apartemen', 1, 1.6),
          L('rumah-bata', 0),
          L('ruko', 2),
          L('rumah-bata-2', 0, 1.3),
          L('toko-roti', 0),
          L('apartemen', 2, 1.6),
          L('rumah-bata', 1),
          L('ruko', 0),
          L('rumah-bata-2', 1, 1.3),
          L('toko-roti', 1),
          L('rumah-bata', 2),
          L('apartemen', 0, 1.6),
          L('ruko', 1),
          L('rumah-bata-2', 2, 1.3),
          L('rumah-bata', 3),
          L('toko-roti', 2),
        ],
      },
    ],
    bands: [
      { rock: 55, tree: 45 },
      { rock: 55, treeGold: 38, crystal: 7 },
      { rock: 50, treeRed: 28, crystal: 22 },
      { rock: 45, treeRed: 30, crystal: 25 },
      { rock: 42, treeRed: 30, crystal: 28 },
    ],
    mapHalf: 18,
    seed: 4242,
    costScale: 2.5,
    completionBonus: 2000,
  },
];
